// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.proto.user;

public interface CreateUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.CreateUserResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.user.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.user.User user = 1;</code>
   * @return The user.
   */
  com.proto.user.User getUser();
}
