// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.proto.user;

public interface DeleteUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.DeleteUserResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
