// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.proto.user;

public interface ListUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.ListUserRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
