// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.proto.user;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
